/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Hospital.LocationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pacif_000
 */
public class ManageBranchesJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Enterprise e;
    /**
     * Creates new form ManageBranchesJPanel
     */
    public ManageBranchesJPanel(JPanel container, Enterprise e) {
        initComponents();
        this.container=container;
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        latitudeJTextField = new javax.swing.JTextField();
        longitudeJTextField = new javax.swing.JTextField();
        locationNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addBranchJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Manage Branches");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 19, -1, -1));

        latitudeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudeJTextFieldActionPerformed(evt);
            }
        });
        add(latitudeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 73, 80, -1));

        longitudeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudeJTextFieldActionPerformed(evt);
            }
        });
        add(longitudeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 111, 80, -1));

        locationNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationNameJTextFieldActionPerformed(evt);
            }
        });
        add(locationNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 149, 80, -1));

        jLabel2.setText("Latitude");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 76, -1, -1));

        jLabel3.setText("Longitude");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 114, -1, -1));

        jLabel4.setText("Location");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 155, -1, -1));

        addBranchJButton.setText("Add Branch");
        addBranchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchJButtonActionPerformed(evt);
            }
        });
        add(addBranchJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 209, -1, -1));

        jLabel5.setText("Enterprise :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 42, -1, -1));

        enterpriseNameJLabel.setText("jLabel6");
        add(enterpriseNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 42, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 209, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void latitudeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudeJTextFieldActionPerformed

    private void longitudeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudeJTextFieldActionPerformed

    private void locationNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationNameJTextFieldActionPerformed

    private void addBranchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchJButtonActionPerformed

        enterpriseNameJLabel.setText(e.getName());
        double lat= Double.parseDouble( latitudeJTextField.getText());
        double lon= Double.parseDouble( longitudeJTextField.getText());
        String name = locationNameJTextField.getText();
        
//        LocationDirectory l= new LocationDirectory();
        LocationDirectory l=e.getLocationDirectory();
        l.addLocation(lat,lon,name);
        
    }//GEN-LAST:event_addBranchJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
       
        container.remove(this);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
        
        
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBranchJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField latitudeJTextField;
    private javax.swing.JTextField locationNameJTextField;
    private javax.swing.JTextField longitudeJTextField;
    // End of variables declaration//GEN-END:variables
}
