/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GuestRole;

import Business.Donor.Details;
import Business.Donor.Donor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.DonorRole.DonorWorkArea;

/**
 *
 * @author pacif_000
 */
public class GuestWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Organization org;
    private UserAccount account;
    private Donor donor;
    private Details dts;
    private Donor d;
    private Enterprise ent;
    private double lat2;
    private double long2;
    /**
     * Creates new form GuestWorkAreaJPanel
     */
    public GuestWorkAreaJPanel(JPanel container, Organization org,Enterprise ent) {
        initComponents();
        this.container=container;
        this.org=org;
//        this.account=account;
//        this.donor=donor;
        this.ent=ent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        latJTextField = new javax.swing.JTextField();
        longJTextField = new javax.swing.JTextField();
        setLocationJButton = new javax.swing.JButton();
        myWorkAreaJButton = new javax.swing.JButton();

        jLabel1.setText("Latitude");

        jLabel2.setText("Longitude");

        latJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latJTextFieldActionPerformed(evt);
            }
        });

        longJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longJTextFieldActionPerformed(evt);
            }
        });

        setLocationJButton.setText("Set Location");
        setLocationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLocationJButtonActionPerformed(evt);
            }
        });

        myWorkAreaJButton.setText("My Work Area>>");
        myWorkAreaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myWorkAreaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(myWorkAreaJButton)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setLocationJButton)
                            .addComponent(latJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(longJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(186, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(latJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(longJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(setLocationJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(myWorkAreaJButton)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void latJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latJTextFieldActionPerformed

    private void longJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longJTextFieldActionPerformed

    private void myWorkAreaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myWorkAreaJButtonActionPerformed

            
        
        for(Organization o: ent.getOrganizationDirectory().getOrganizationList()){
            
//        Organization o=(DonorOrganization) org;
        if(o instanceof DonorOrganization){
           DonorOrganization or=(DonorOrganization) o;
        for (Employee e : or.getEmployeeDirectory().getEmployeeList()){
            
            
            
            
            d = (Donor)e;
            if((d.getDetails().getLatitude()==lat2 && d.getDetails().getLongitude()==long2)){
            
                for(UserAccount acct: org.getUserAccountDirectory().getUserAccountList()){
                 
                    Object [] ob= new Object[1];
                    ob[0]=acct.getUsername();
                    if(ob[0].equals(d.getName())){
                        account=acct;
                        account.setUsername(d.getName());
                 CardLayout layout = (CardLayout) container.getLayout();       
                container.add("Donor Work Area",new DonorWorkArea(container,org,account,d,ent));
                layout.next(container);
                }
                }  
            
            }
            
        
        }
        }
        
        }

    }//GEN-LAST:event_myWorkAreaJButtonActionPerformed

    private void setLocationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLocationJButtonActionPerformed
        
        double long1 =Double.parseDouble(longJTextField.getText());
        double lat1 =Double.parseDouble(latJTextField.getText());
        
        lat2=lat1;
        long2=long1;
//        for(Organization o: ent.getOrganizationDirectory().getOrganizationList())
////        Organization o=(DonorOrganization) org;
//        if(o instanceof DonorOrganization){
//           DonorOrganization or=(DonorOrganization) o;
//        for (Employee e : or.getEmployeeDirectory().getEmployeeList()){
//            Donor d = (Donor)e;
//            if(d.getDetails().getLatitude()==lat1 &&d.getDetails().getLongitude()==long1){
//                
//                
//            
//            
//            }
//        }
//        }
        
    }//GEN-LAST:event_setLocationJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField latJTextField;
    private javax.swing.JTextField longJTextField;
    private javax.swing.JButton myWorkAreaJButton;
    private javax.swing.JButton setLocationJButton;
    // End of variables declaration//GEN-END:variables
}
