/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.Donor.Details;
import Business.Donor.Donor;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author pacif_000
 */
public class AddDetails extends javax.swing.JPanel {

    private JPanel container;
    private Organization org;
    private UserAccount account;
    private Details dts;
    private Donor d;
    private Enterprise ent;
    
    
    /**
     * Creates new form AddDetails
     */
    public AddDetails(JPanel container, Organization org, UserAccount account, Enterprise ent) {
        initComponents();
        this.container=container;
        this.org=org;
        this.account=account;
        this.ent=ent;
        dts=new Details();
        userNameJLabel.setText(account.getUsername());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberJTextField = new javax.swing.JTextField();
        relationJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        latitudeJTextField = new javax.swing.JTextField();
        longitudeJTextField = new javax.swing.JTextField();
        setLocationJButton = new javax.swing.JButton();
        addContactsJButtton = new javax.swing.JButton();
        myWorkAreaJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        locationNameJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bloodTypeJTextField = new javax.swing.JTextField();
        addBloodTypeJButton = new javax.swing.JButton();

        jLabel1.setText("Welcome ");

        userNameJLabel.setText("jLabel2");

        jLabel2.setText("Add Donor Details");

        jLabel3.setText("Relation");

        jLabel4.setText("Number");

        jLabel5.setText("Location Details");

        jLabel6.setText("Latitude");

        jLabel7.setText("Longitude");

        setLocationJButton.setText("Set Location");
        setLocationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLocationJButtonActionPerformed(evt);
            }
        });

        addContactsJButtton.setText("Add Emergency Contacts");
        addContactsJButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContactsJButttonActionPerformed(evt);
            }
        });

        myWorkAreaJButton.setText("My Work Area>>");
        myWorkAreaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myWorkAreaJButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Name of Location");

        jLabel9.setText("Blood Type : ");

        addBloodTypeJButton.setText("Add Blood Type");
        addBloodTypeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBloodTypeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(relationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(userNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addContactsJButtton)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addBloodTypeJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bloodTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(myWorkAreaJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(setLocationJButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(locationNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(longitudeJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(latitudeJTextField, javax.swing.GroupLayout.Alignment.LEADING)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(bloodTypeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addBloodTypeJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(userNameJLabel))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(relationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(1, 1, 1)
                                .addComponent(addContactsJButtton)
                                .addGap(13, 13, 13))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(latitudeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(longitudeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(locationNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(setLocationJButton)
                        .addGap(22, 22, 22)
                        .addComponent(myWorkAreaJButton)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void myWorkAreaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myWorkAreaJButtonActionPerformed
        
        String username=account.getUsername();
//        if(account.getUsername().equals(username)){
        for(Organization o: ent.getOrganizationDirectory().getOrganizationList()){
//        Organization o=(DonorOrganization) org;
        if(o instanceof DonorOrganization){
           DonorOrganization or=(DonorOrganization) o;
        for (Employee e : or.getEmployeeDirectory().getEmployeeList()){
             
            Object[] em = new Object[1];
                em[0]=e.getName();
                if(em[0].equals(username)){
                    
             d = (Donor)e;
             CardLayout layout = (CardLayout) container.getLayout();
            container.add("Donor Work Area",new DonorWorkArea(container,org,account,d,ent));
            layout.next(container);
            }
            
            }
          }
        }
        
        
//        }
        
    }//GEN-LAST:event_myWorkAreaJButtonActionPerformed

    private void setLocationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLocationJButtonActionPerformed

        String username=account.getUsername();
        double lat = (Double.parseDouble(latitudeJTextField.getText()));
        double lon =(Double.parseDouble(longitudeJTextField.getText()));
        String locationName= locationNameJTextField.getText();

        for(Organization o: ent.getOrganizationDirectory().getOrganizationList()){

        if(o instanceof DonorOrganization){
           DonorOrganization or=(DonorOrganization) o;
        for (Employee e : or.getEmployeeDirectory().getEmployeeList()){
            
            Object[] em = new Object[1];
                em[0]=e.getName();
                if(em[0].equals(username)){
                    
             d = (Donor)e;
             d.addDetails(lat,lon,locationName);
            }
            
            }
        }
        }
        
        numberJTextField.setText(username);
        
       // dts.setDonor(d);
//        }
       
    }//GEN-LAST:event_setLocationJButtonActionPerformed

    private void addContactsJButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactsJButttonActionPerformed
        
        String rel = relationJTextField.getText();
        long num=Long.parseLong(numberJTextField.getText());
        String username=account.getUsername();
        
//        if(account.getUsername().equals(username)){
        for(Organization o: ent.getOrganizationDirectory().getOrganizationList()){
//        Organization o=(DonorOrganization) org;
        if(o instanceof DonorOrganization){
           DonorOrganization or=(DonorOrganization) o;
        for (Employee e : or.getEmployeeDirectory().getEmployeeList()){
//            if(e.getName().equals(username)){
                
                Object[] em = new Object[1];
                em[0]=e.getName();
                if(em[0].equals(username)){
                    
             d = (Donor)e;
             d.addContactDetails(rel,num);
            }
            }
        }
        }
        
        
        
        relationJTextField.setText("");
        numberJTextField.setText("");
//        }
    }//GEN-LAST:event_addContactsJButttonActionPerformed

    private void addBloodTypeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBloodTypeJButtonActionPerformed
        
        String type= bloodTypeJTextField.getText();
        String username=account.getUsername();
        
//        if(account.getUsername().equals(username)){
        for(Organization o: ent.getOrganizationDirectory().getOrganizationList()){
//        Organization o=(DonorOrganization) org;
        if(o instanceof DonorOrganization){
           DonorOrganization or=(DonorOrganization) o;
        for (Employee e : or.getEmployeeDirectory().getEmployeeList()){
//            if(e.getName().equals(username)){
                
                Object[] em = new Object[1];
                em[0]=e.getName();
                if(em[0].equals(username)){
                    
             d = (Donor)e;
             d.addBloodDetails(type);
            }
            }
        }
        }
        
        
        
    }//GEN-LAST:event_addBloodTypeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBloodTypeJButton;
    private javax.swing.JButton addContactsJButtton;
    private javax.swing.JTextField bloodTypeJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField latitudeJTextField;
    private javax.swing.JTextField locationNameJTextField;
    private javax.swing.JTextField longitudeJTextField;
    private javax.swing.JButton myWorkAreaJButton;
    private javax.swing.JTextField numberJTextField;
    private javax.swing.JTextField relationJTextField;
    private javax.swing.JButton setLocationJButton;
    private javax.swing.JLabel userNameJLabel;
    // End of variables declaration//GEN-END:variables
}
